name: riplay-rp-test
on: [push, pull_request]

jobs:
  test-build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install sourcemod deps
        run: |
          sudo apt-get update && sudo apt-get install libc6-i386 lib32stdc++6 ncftp


      - name: Compile
        run: |
          ./compile_all_linux.sh


      - name: Upload compiled plugins
        uses: actions/upload-artifact@v2
        with: 
          name: compiled
          path: compiled/

      - name: Upload to dev server
        if: ${{ github.ref == 'master' && github.event_name == 'push' }}
        env: 
          ftp_password: ${{ secrets.FTPPassword }}
        run: |
          ncftpput -u rp_test -p $ftp_password cpu-linux.riplay.fr plugins compiled/*
